name: ace
version: 0.1.4-dev+10.28.2013
author: Ross Smith <ross.dart.lang@gmail.com>
description: High performance code editor for the web.
homepage: https://github.com/rmsmith/ace.dart
documentation: http://rmsmith.github.com/ace.dart/ace.html
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
dev_dependencies:
  bench: '>=0.2.20'
  browser: '>=0.9.0'
  unittest: '>=0.9.0'
